// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_Final.clases;

#nullable disable

namespace ProyectoFinal.Migrations
{
    [DbContext(typeof(RestauranteDataContext))]
    [Migration("20230328213319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_Final.clases.Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<float>("importe")
                        .HasColumnType("real");

                    b.Property<float>("iva")
                        .HasColumnType("real");

                    b.Property<int>("mesa")
                        .HasColumnType("int");

                    b.Property<string>("producto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int?>("tipo_cobro")
                        .HasColumnType("int");

                    b.Property<int>("tipo_pedido")
                        .HasColumnType("int");

                    b.Property<float>("total")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Proyecto_Final.clases.Producto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precio")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Hamburguesa con queso",
                            precio = 99.989999999999995
                        },
                        new
                        {
                            id = 2,
                            nombre = "Coca cola 600ml",
                            precio = 19.989999999999998
                        },
                        new
                        {
                            id = 3,
                            nombre = "Pepsi 600ml",
                            precio = 15.99
                        },
                        new
                        {
                            id = 4,
                            nombre = "Papas fritas medianas",
                            precio = 49.990000000000002
                        },
                        new
                        {
                            id = 5,
                            nombre = "Nuggets de pollo (6 piezas)",
                            precio = 89.989999999999995
                        });
                });

            modelBuilder.Entity("Proyecto_Final.clases.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            apellidos = "Gomez",
                            correo = "prueba@gmail.com",
                            nombre = "Adamaris",
                            password = "1234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
