version: '3.1'

services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    ports:
      - '5506:3306'
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST_db
    depends_on:
      - db